name: vlm_ros_env
channels:
  - robostack-staging
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ros-humble-ros-base
  - ros-humble-cv-bridge
  - ros-humble-rosbag2
  - ros-humble-rosbag2-storage-mcap
  - ros-humble-image-transport
  - numpy
  - pip
  - pip:
    - torch
    - torchvision
    - pillow
    - rosbags  # For reading ROS1 .bag files and ROS2 .mcap/.db3 files easily
    - matplotlib
